### ISSUE TITLE
OCI Dashboards -ERROR: rpc error: code = Unknown desc = Get "xyz"  EOF (SQLSTATE HV000)

### ISSUE THREAD

**Issue by martinberger-ch** [turbot/steampipe-mod-oci-insights#59]
**Is your feature request related to a problem? Please describe.**

I have a large setup in OCI, on several dashboards like the OCI Compute Instance Age Report I get this error:

ERROR: rpc error: code = Unknown desc = Get "https://iaas.eu-zurich-1.oraclecloud.com/20160918/instances?compartmentId=ocid1.compartment.oc1..aaaaaaabcdefghsa&limit=1000": EOF (SQLSTATE HV000)

I use these versions in WSL2 on Ubuntu:

$ steampipe plugin list
+--------------------------------------------------+---------+-------------+
| Name                                             | Version | Connections |
+--------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/oci@latest       | 0.13.0  | oci         |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.2.0   | steampipe   |
+--------------------------------------------------+---------+-------------+

**Additional context**

This is a screenhot with the error.

![screenshot_dashboard](https://user-images.githubusercontent.com/56437524/163691012-dd4342f2-c028-4dd3-bcc1-6bb0c537d95a.png)

**Describe the solution you'd like**
A dashboard which works.

**Comment by e-gineer** [comment]
Thanks @martinberger-ch for reporting this - sorry it's not working as expected.

Does it fail every time, or work sometimes when you refresh?

I know @kaidaguerre has done some good work to eliminate EOF errors in v0.14.x of Steampipe, suggest we test this again once that is out (soon).

**Comment by martinberger-ch** [comment]
> 

Hi, this happens every time. A page refresh does not help.

**Comment by cbruno10** [comment]
Hey @martinberger-ch , we tried to reproduce by creating instances in eu-zurich-1 and running the same dashboard on Mac and Windows WSL2, but unfortunately were unable to reproduce the same errors you were seeing.

To help us better reproduce the issue, can you please provide a few details below:
- What version of the Steampipe CLI + OCI plugin are you using?
- Can you please provide your `oci.spc` file (with all sensitive information removed)?
- Do you have any instances in regions other than eu-zurich-1? If so, can you please update your `oci.spc` file to query those regions instead and see if you receive the same dashboard errors?
- Do other dashboards load ok, or do you encounter errors on those too? If so, which dashboards do you encounter errors on?
- Are you able to run the example queries from https://hub.steampipe.io/plugins/turbot/oci/tables/oci_core_instance? If not, can you please provide the output + errors you're receiving?

Thanks!

**Comment by cbruno10** [comment]
Hi @martinberger-ch , we haven't heard back from you in a while, so we're closing this issue. If you're still experiencing this issue, or any others, feel free to re-open and we can discuss more. Thanks!
